<div class="jumbotron">
    <h1 class="text-center">管理员信息一览:</h1><br>
    <table class="table table-dark table-hover">
        <thead>
            <tr>
                <th>管理员ID</th>
                <th>姓名</th>
                <th>角色</th>
                <th>邮箱</th>
                <th>账户创建日期</th>
                <th>最后登录日期</th>
                <th>登录次数</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>John</td>
                <td>Doe</td>
                <td>超级管理员</td>
                <td>john@example.com</td>
                <td>john@example.com</td>
                <td>john@example.com</td>
                <td>john@example.com</td>
            </tr>
            <tr>
                <td>Mary</td>
                <td>Moe</td>
                <td>Moe</td>
                <td>mary@example.com</td>
                <td>mary@example.com</td>
                <td>mary@example.com</td>
                <td>mary@example.com</td>
            </tr>
            <tr>
                <td>July</td>
                <td>Dooley</td>
                <td>Dooley</td>
                <td>july@example.com</td>
                <td>july@example.com</td>
                <td>july@example.com</td>
                <td>july@example.com</td>
            </tr>
        </tbody>
    </table>
</div>